-- Create storage integration for Azure blob access
CREATE OR REPLACE STORAGE INTEGRATION ags_raw_integration
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = AZURE
  ENABLED = TRUE
  AZURE_TENANT_ID = '3f376729-966a-408f-bd2e-e81054cd298f'
  STORAGE_ALLOWED_LOCATIONS = ('azure://etltestcase.blob.core.windows.net/ags-raw-data/');

-- Grant usage on integration
GRANT USAGE ON INTEGRATION ags_raw_integration TO ROLE ACCOUNTADMIN;

-- Create external stage pointing to Azure blob container
CREATE OR REPLACE STAGE AGS_RAW_STAGE
  URL = 'azure://etltestcase.blob.core.windows.net/ags-raw-data/'
  STORAGE_INTEGRATION = ags_raw_integration;

-- Create file format for CSV files
CREATE OR REPLACE FILE FORMAT ags_csv_format
  TYPE = 'CSV'
  SKIP_HEADER = 1
  FIELD_DELIMITER = ','
  RECORD_DELIMITER = '\n'
  NULL_IF = ('NULL', 'null', '');

-- Create METRICS table
CREATE TABLE IF NOT EXISTS AGS_RAW.PUBLIC.METRICS (
  ID INT,
  VALUE FLOAT,
  TIMESTAMP TIMESTAMP,
  SOURCE VARCHAR
);

-- Create STATISTICS table
CREATE TABLE IF NOT EXISTS AGS_RAW.PUBLIC.STATISTICS (
  STAT_NAME VARCHAR,
  STAT_VALUE FLOAT,
  CREATED_AT TIMESTAMP
);

-- Create DICTIONARY table
CREATE TABLE IF NOT EXISTS AGS_RAW.PUBLIC.DICTIONARY (
  KEY VARCHAR,
  VALUE VARCHAR,
  DESCRIPTION VARCHAR
);

-- Create stored procedure to load metrics CSV
CREATE OR REPLACE PROCEDURE AGS_RAW.PUBLIC.LOAD_METRICS_CSV(stage_name VARCHAR, file_name VARCHAR, id_col VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
  load_count INT;
BEGIN
  COPY INTO AGS_RAW.PUBLIC.METRICS
  FROM @AGS_RAW_STAGE
  FILE_FORMAT = (FORMAT_NAME = 'ags_csv_format', ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE)
  ON_ERROR = CONTINUE
  FORCE = TRUE;
  
  SELECT COUNT(*) INTO load_count FROM AGS_RAW.PUBLIC.METRICS;
  
  RETURN 'LOAD_METRICS_CSV completed for: ' || file_name;
END;
$$;

-- Create stored procedure to load statistics
CREATE OR REPLACE PROCEDURE AGS_RAW.PUBLIC.LOAD_STATISTICS_SQL(stage_name VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
BEGIN
  INSERT INTO AGS_RAW.PUBLIC.STATISTICS (STAT_NAME, STAT_VALUE, CREATED_AT)
  SELECT 'total_metrics', COUNT(*), CURRENT_TIMESTAMP()
  FROM AGS_RAW.PUBLIC.METRICS;
  
  RETURN 'LOAD_STATISTICS_SQL completed';
END;
$$;

-- Create stored procedure to load dictionary
CREATE OR REPLACE PROCEDURE AGS_RAW.PUBLIC.LOAD_DICTIONARY_SQL(stage_name VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
BEGIN
  INSERT INTO AGS_RAW.PUBLIC.DICTIONARY (KEY, VALUE, DESCRIPTION)
  VALUES ('version', '1.0', 'AGS Raw Data Version');
  
  INSERT INTO AGS_RAW.PUBLIC.DICTIONARY (KEY, VALUE, DESCRIPTION)
  VALUES ('loaded_at', CURRENT_TIMESTAMP()::VARCHAR, 'Data load timestamp');
  
  RETURN 'LOAD_DICTIONARY_SQL completed';
END;
$$;
