  dev:
    blob_storage:
      container_name: ags-raw-data
      folder_prefix: ''
      secret_name: blob-connection-secret
      storage_account: etltestcase
    key_vault: etl-test-agent-kv
    snowflake:
    - account: LJIFTPU-OZ47012
      database: AGS_RAW
      private_key:
        secret_name: snowflake-private-key
      role: ACCOUNTADMIN
      schema: PUBLIC
      stage: AGS_RAW_STAGE
      user: ABESHITH
      warehouse: COMPUTE_WH
      tables:
      - name: METRICS
      - name: STATISTICS
      - name: DICTIONARY
  dev_v1:
    blob_storage:
      container_name: hospitaldata
      folder_prefix: ''
      secret_name: blob-connection-secret
      storage_account: etltestcase
    key_vault: etl-test-agent-kv
    snowflake:
    - account: LJIFTPU-OZ47012
      database: LANDING
      private_key:
        local_file: rsa_key.p8
        secret_name: snowflake-private-key
      role: ACCOUNTADMIN
      schema: LND
      stage: hospitaldata
      tables:
      - blob_path: hospitaldata_{DATE}.csv
        file_format: my_csv_format
        name: raw_data
        on_error: CONTINUE
      - blob_path: audit_log_{DATE}.csv
        file_format: my_csv_format
        name: audit_log
        on_error: CONTINUE
      user: ABESHITH
      warehouse: COMPUTE_WH
  dev_v2:
    key_vault: etl-test-agent-kv
    snowflake:
    - account: OGQRJWE-KR90576
      database: ETL_RAW
      private_key:
        secret_name: snowflake-private-key-v2
      role: ACCOUNTADMIN
      schema: LIGHTBOX
      shares:
      - database: SHARED_DB
        name: TERMINAL_SHARE
        schema: SHARED_SCHEMA
      tables_to_copy:
      - filename: ddl/create_tables.sql
      - filename: ddl/create_assessments.sql
      user: ABESHITH
      warehouse: COMPUTE_WH
  dev_v3:
    blob_storage:
      base_prefix: global_energy_monitor
      container_name: gem-geojson-data
      secret_name: blob-connection-secret
      storage_account: etltestcase
      target_prefix: processed
    key_vault: etl-test-agent-kv
    load:
      pattern_ext: \.geojson
    snowflake:
    - account: OGQRJWE-KR90576
      database: LANDING
      load_mode: replace
      pipe_target_table: GAS_PIPELINES
      private_key:
        secret_name: snowflake-private-key-v3
      role: ACCOUNTADMIN
      schema: LND
      stage: GLOBAL_ENERGY_MONITOR_STAGE
      storage_integration: ETL_PRODUCT_INTEGRATION_LND
      term_target_table: LNG_TERMINALS
      user: ABESHITH
      warehouse: COMPUTE_WH
  table: invalid_target_table
