[theme]
primaryColor = "#5236AB"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F7F9"
textColor = "#333333"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
